### ISSUE TITLE
Broken HTML links

### ISSUE THREAD

**Issue by n-eq** [internetarchive/dweb-archivecontroller#9]
** Context **
The following links in the README file are broken

```
* [Archive.org](https://dweb.archive.org/details) bootstrap into the Archive's page
* [Examples](https://dweb.me/examples) examples
```
Archive.org bootstrap into the Archive's page
Examples examples

**Comment by mitra42** [comment]
Thanks - https://dweb.archive.org is the link to the Archive's page, and  dweb.me/examples is obsolete.  I've fixed them.

**Comment by n-eq** [comment]
Perfect, closing the issue then.
